---

- name: Get AWX operator releases
  ansible.builtin.uri:
    url: https://api.github.com/repos/ansible/awx-operator/releases
    return_content: true
  register: awx_operator_releases

- name: Deploy kustomization.yaml template
  ansible.builtin.template:
    src: kustomization.yaml.j2
    dest: "{{ kustomize_directory }}/kustomization.yaml"
    mode: 0644
  vars:
    awx_operator_latest_tag: "{{ awx_operator_releases['json'][0]['tag_name'] }}"

- name: Get state of AWX operator deployment
  kubernetes.core.k8s_info:
    kind: Deployment
    name: awx-operator-controller-manager
    namespace: "{{ awx_namespace }}"
  register: awx_operator_deployment_info

- name: Apply ressources from kustomize directory
  ansible.builtin.command:
    cmd: kubectl apply -k {{ kustomize_directory }}
  when: awx_operator_deployment_info.resources | length == 0

- name: Wait for running state of awx-operator-controller-manager pods (timeout set to 20 minutes)
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ awx_namespace }}"
    label_selectors:
      - control-plane = controller-manager
    wait: true
    wait_sleep: 10
    wait_timeout: 600
  register: awx_operator_controller_manager_pods
