---
exposed_node_port: 30080

minikube_download_directory: "{{ ansible_user_dir }}"

minikube_additional_start_parameter: "--cpus=4 --memory=6g --addons=ingress --container-runtime=containerd --ports={{ exposed_node_port }}:{{ exposed_node_port }}"
